# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 14:58
from __future__ import unicode_literals

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sola', models.CharField(blank=True, max_length=100)),
                ('regija', models.CharField(blank=True, max_length=100)),
                ('datum_plesa', models.DateTimeField(blank=True, null=True)),
                ('starost', models.DateTimeField(blank=True, null=True)),
                ('spol', models.NullBooleanField()),
                ('visina', models.IntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilnaSlika',
            fields=[
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('slika', models.ImageField(default='default-avatar.jpg', upload_to='profilne_slike')),
                ('slika_nalozena_cas', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialnaOmrezja',
            fields=[
                ('user', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('snapchat', models.CharField(blank=True, max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('google', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('soundcloud', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
