# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_auto_20161226_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
