# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import profil.validators


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_auto_20170114_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilnaslika',
            name='slika',
            field=models.FileField(default='default-avatar.jpg', upload_to='profilne_slike', validators=[profil.validators.validate_file_extension]),
        ),
    ]
