# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0004_auto_20170114_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilnaslika',
            name='slika',
            field=models.ImageField(default='default-avatar.jpg', upload_to='profilne_slike'),
        ),
    ]
