# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_auto_20161226_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='bio',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='datum_plesa',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='sola',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='starost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='visina',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialnaomrezja',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialnaomrezja',
            name='google',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialnaomrezja',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialnaomrezja',
            name='snapchat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialnaomrezja',
            name='soundcloud',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='socialnaomrezja',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
