# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0008_profil_socialnaomrezja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='user',
        ),
        migrations.RemoveField(
            model_name='socialnaomrezja',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profil',
        ),
        migrations.DeleteModel(
            name='SocialnaOmrezja',
        ),
    ]
