# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sporocilo',
            name='posiljatelj',
        ),
        migrations.RemoveField(
            model_name='sporocilo',
            name='prejemnik',
        ),
        migrations.DeleteModel(
            name='Sporocilo',
        ),
    ]
