# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 11:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontakt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prvi_stik', models.DateTimeField(auto_now_add=True)),
                ('oseba1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oseba1', to=settings.AUTH_USER_MODEL)),
                ('oseba2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oseba2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sporocilo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('besedilo', models.TextField(blank=True)),
                ('cas_posiljanja', models.DateTimeField(auto_now_add=True)),
                ('posiljatelj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiljatelj', to=settings.AUTH_USER_MODEL)),
                ('prejemnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prejemnik', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
