# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontakt',
            name='nova_sporocila',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kontakt',
            name='zadnji_stik',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
